### ISSUE TITLE
Loading best_model.hdf5 for Xception Tensorflow

### ISSUE THREAD

**Issue by praneet195** [marco-willi/camera-trap-classifier#21]
When I try to load the weights into the Xception model of Tensorflow, i'm getting the following error:
ValueError: You are trying to load a weight file containing 88 layers into a model with 80 layers.
Have any changes been made to the Xception model being used in this repo?
Regards,
praneet195

**Comment by marco-willi** [comment]
Hi praneet195,

The trained Xception model from [here](https://github.com/marco-willi/camera-trap-classifier/blob/master/docs/trained_models.md#species-model) has multiple output heads (8 in total) in order to classify not just species but also count categories and several behaviors. Here is where I define the Xception architecture by importing it from Keras [Link](https://github.com/marco-willi/camera-trap-classifier/blob/master/camera_trap_classifier/training/prepare_model.py#L230) and where I am adding the heads: [Link](https://github.com/marco-willi/camera-trap-classifier/blob/master/camera_trap_classifier/training/prepare_model.py#L248). I hope this helps.
Best, Marco

**Comment by praneet195** [comment]
Thank you, that definitely solves my issue
