### ISSUE TITLE
ctc.train error

### ISSUE THREAD

**Issue by mehrnoushmalek** [marco-willi/camera-trap-classifier#25]
Hi Marco,

Thanks a lot for this super cool package. I'm an R user but the documentation helped a lot. I  used another package written in R (MLWIC), and I want to know if I get better result with your code, and see if it's faster, as the other one is super slow.

So as a background. I'm using the docker version with labels (only cpu). I created my csv file, and the image column has the path to my images (/data/train/images/*.JPG). I have around 38000 images with labels. The json file was created. and when I looked at it everything made sense. Then I ran the code to create the tfr files ( test and validation are around 1800, and the rest are the training).  So it created 7 train *.tfrecodr, and one for each validation and test. When I opened the label_mapping.json, everything looked legit:
`{"count": {"1": 0}, "species": {"buffalo": 1, "waterbuck": 17, "darkness": 2, "jackal": 11, "giraffe": 5, "hartebeest": 8, "hare": 7, "impala": 10, "vegetation": 16, "eland": 3, "grantgazelle": 6, "humanactivities": 9, "lion": 12, "spottedhyena": 14, "baboon": 0, "elephant": 4, "zebra": 18, "servalcat": 13, "unknown": 15}}`.
Then to train the model, I followed your documentaion, and just changed the -label, and added the weight_loss parameter:
`sudo docker exec ctc ctc.train -train_tfr_path /data/tfr_files/ -val_tfr_path /data/tfr_files/ -test_tfr_path /data/tfr_files/ -class_mapping_json /data/tfr_files/label_mapping.json -run_outputs_dir /data/run1/ -model_save_dir /data/save1/ -model small_cnn -labels species count  -labels_loss_weights 1 0.5 -batch_size 16 -n_cpus 4 -n_gpus 0 -buffer_size 16 -max_epochs 70 -color_augmentation full_randomized`
 but I get bunch of errors:

`Traceback (most recent call last):
  File "/usr/local/bin/ctc.train", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/camera_trap_classifier/train.py", line 489, in main
    output_loss_weights=args['labels_loss_weights'])
  File "/usr/local/lib/python3.5/dist-packages/camera_trap_classifier/training/prepare_model.py", line 322, in create_model
    metrics=[accuracy, top_k_accuracy])
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/checkpointable/base.py", line 474, in _method_wrapper
    method(self, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/engine/training.py", line 617, in compile
    output_loss = weighted_loss(y_true, y_pred, sample_weight, mask)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/engine/training_utils.py", line 598, in weighted
    score_array = fn(y_true, y_pred)
  File "/usr/local/lib/python3.5/dist-packages/camera_trap_classifier/training/utils.py", line 93, in masked_loss_function
    return loss_function(y_true * mask, y_pred * mask)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/backend.py", line 3630, in sparse_categorical_crossentropy
    logits = array_ops.reshape(output, [-1, int(output_shape[-1])])
TypeError: int returned non-int (type NoneType)`

I would be grateful if you can let me know what the issue is, and how I can resolve it. I don't know much about python, so sorry in advance if I said something that didn't make sense.

**Comment by marco-willi** [comment]
Hi mehrnoushmalek

Thanks for your interest in this repository. I'm not entirely sure what goes wrong but one thing I noticed is the 'count' label you are using. According to the label_mapping.json you only provide the model with one count category ("1"). Presumably because you don't record the number of individuals? This might cause an issue because the number of distinct categories per label (species / count) should be at least 2--otherwise there is nothing for the model to learn. Does that make sense? You could verify that by trying to run the model with:

```
-labels species -labels_loss_weights 1.0
```

Let me know if that solves the issue.

Additionally, please note that the model architecture "small_cnn" is more of a toy model that won't produce very good results (but maybe still good enough). The smallest 'serious' model is "ResNet18".

For a use case with a larger model and the settings used to train it, please refer to: https://github.com/marco-willi/camera-trap-classifier/blob/master/docs/trained_models.md

**Comment by mehrnoushmalek** [comment]
Thanks a lot for getting back to me. So for counts I need to go through all images and add how many animals are in the picture, and update the count? When I ran this (with and without Docker):
`ctc.train -train_tfr_path ~/Projects/OPC/tfr_files/ -val_tfr_path ~/data/tfr_files/ -test_tfr_path ~/data/tfr_files/ -class_mapping_json ~/data/tfr_files/label_mapping.json -run_outputs_dir ~/data/run1/ -model_save_dir ~/Projects/OPC/save1/ -model ResNet18 -labels species -labels_loss_weights 1.0  -batch_size 128 -n_cpus 10 -n_gpus 1 -buffer_size 512 -max_epochs 70`

I get this:
`Shape must be rank 0 but is rank 1 for 'metrics/top_k_accuracy/cond/Switch' (op: 'Switch') with input shapes: [?], [?].`
Is this the error you were referring when only one counts is provided?
regarding the previous error, Is it possible that ids or counts become non-integer when the csv is read in the code? When I open the csv file, it says it's a number, but when I open the json file in R, this is what I get:
`$labels[[1]]$count
[1] "1"

$labels[[1]]$species
[1] "baboon"



$images
$images[[1]]
[1] "/data/images/BABOON__2019-01-09__08-43-37(1)_flipped.JPG.`

**Comment by marco-willi** [comment]
Sorry for my late reply. Whether you want the model to be able to count animals is up to you. If you want that capability you need to label the images with correct counts. If you don't want that capability you don't need to and you can train the model without count labels.

At the moment I can't tell what goes wrong. It seems like the input shape of you data is unkonwn / can't be determined, that's why I thought something with the labels output might be wrong. Can you verify that the tfrecords files have been created correctly? Does the size of the files make sense? Additionally, can you provide / paste the log files that are being generated by the code when generating the tfrecord files and when you start the training? 

Also, it seems like the error is now different? Not sure, but maybe it helps to create the tfrecord files without the counts (although that is not supposed to be necessary) and then train the model with only the species labels.
